formats:
- hdf5
languages:
- py
paths:
  path_to_benchmarks: benchmarks
  path_to_tmp: components/tmp
  path_to_root: /home/dev/hpffbench
  path_to_results: components/results
iterations: 1
runs:
  run04:
    X:
    - - 134217728
    - []
parallel: true
par_backend: MPI
ranks:
- 5
nodes:
- 1
variable_to_benchmark:
- X
only data: false
use spack env: true
max processes: 20
slurm options: '

  #SBATCH --partition=compute

  #SBATCH --account=ku0598

  #SBATCH --constraint="[cell02]"

  #SBATCH --mem=0

  #SBATCH --cpu-freq=High

  #SBATCH --distribution=block:cyclic

  #SBATCH --time=02:00:00

  #SBATCH --exclusive

  #SBATCH --output=log/log-%j/log.%j.txt

  #SBATCH --error=log/log-%j/log.%j.err

  '
spack env:
  test-env-test4:
    target:
    - hdf5
    - hdf5: subfiling
    - netcdf4
    - zarr
    language:
    - py
    - c
    packages:
      python:
        versions:
        - 3.11.14
        fresh: true
      openmpi:
        versions:
        - 5.0.8
        fresh: true
      hdf5:
        versions:
        - 1.14.6
        variants: ~cxx~fortran+hl~ipo~java~map+mpi+shared+subfiling~szip+threadsafe+tools
      argobots:
        versions:
        - main
        fresh: true
      netcdf-c:
        versions:
        - 4.9.2
        variants: build_system=cmake
      py-mpi4py:
        versions:
        - 4.0.1
      py-h5py:
        versions:
        - 3.14.0
      py-netcdf4:
        versions:
        - 1.7.1
    compiler: gcc@11.4
    additional: pip install zarr==3.0.5 py-spy
    install: true
  test-env-async:
    target:
    - hdf5: async
    language:
    - c
    packages:
      python:
        versions:
        - 3.11.14
        fresh: true
      openmpi:
        versions:
        - 5.0.8
      hdf5:
        versions:
        - 1.14.6
        variants: ~cxx~fortran+hl~ipo~java~map+mpi+shared+subfiling~szip+threadsafe+tools
      hdf5-vol-async:
        versions:
        - develop
      argobots:
        versions:
        - main
        fresh: true
      netcdf-c:
        versions:
        - 4.9.2
        variants: build_system=cmake
      py-mpi4py:
        versions:
        - 4.0.1
      py-h5py:
        versions:
        - 3.14.0
      py-netcdf4:
        versions:
        - 1.7.1
    compiler: gcc@11.4
delete envs: false
