formats:
- hdf5
languages:
- py
paths:
  path_to_benchmarks: components/benchmarks
  path_to_tmp: components/tmp
  path_to_config: components/handler
  path_to_visuals: components/visualize
  path_to_root: /work/ku0598/k203191/dkrz_dev
  path_to_results: components/results
  path_profiling: components/profiling
iterations: 2
runs:
  run03:
    X:
    - - 134217728
    - []
parallel: true
par_backend: MPI
ranks:
- 1
nodes:
- 1
variable_to_benchmark:
- X
only data: false
use spack env: true
max processes: 20
slurm options: '

  #SBATCH --wait

  #SBATCH --partition=compute

  #SBATCH --account=ku0598

  #SBATCH --constraint="[cell02]"

  #SBATCH --mem=0

  #SBATCH --cpu-freq=High

  #SBATCH --distribution=block:cyclic

  #SBATCH --time=02:00:00

  #SBATCH --exclusive

  #SBATCH --output=log/log-%j/log.%j.txt

  #SBATCH --error=log/log-%j/log.%j.err

  '
spack env:
  test-env-1:
    target:
    - hdf5
    - hdf5: subfiling
    - netcdf4
    - zarr
    language:
    - py
    - c
    packages:
      python:
        versions:
        - 3.11.9
        fresh: true
      openmpi:
        versions:
        - 5.0.5
        fresh: true
      hdf5:
        versions:
        - 1.14.5
        variants: ~cxx~fortran+hl~ipo~java~map+mpi+shared+subfiling~szip+threadsafe+tools
        fresh: true
      argobots:
        versions:
        - main
        fresh: true
      netcdf-c:
        versions:
        - 4.9.2
        variants: build_system=cmake
        fresh: true
      py-mpi4py:
        versions:
        - 4.0.1
      py-h5py:
        versions:
        - 3.12.1
      py-netcdf4:
        versions:
        - 1.7.1
    compiler: gcc@11.2.0
    additional: pip install zarr==3.0.5 py-spy
  test-env-async:
    target:
    - hdf5: async
    language:
    - c
    packages:
      python:
        versions:
        - 3.11.9
        fresh: true
      openmpi:
        versions:
        - 5.0.5
        fresh: true
      hdf5:
        versions:
        - 1.14.5
        variants: ~cxx~fortran+hl~ipo~java~map+mpi+shared+subfiling~szip+threadsafe+tools
        fresh: true
      hdf5-vol-async:
        versions:
        - develop
      argobots:
        versions:
        - main
        fresh: true
      netcdf-c:
        versions:
        - 4.9.2
        variants: build_system=cmake
        fresh: true
      py-mpi4py:
        versions:
        - 4.0.1
      py-h5py:
        versions:
        - 3.12.1
      py-netcdf4:
        versions:
        - 1.7.1
    compiler: gcc@11.2.0
delete envs: false
profiler: true
