language: py
format: hdf5
run_command:
  serial: python -m scorep --thread=pthread --instrumenter-type=cTrace {runnable}
  MPI: mpiexec -n python -m scorep --mpp=mpi --thread=pthread --instrumenter-type=cTrace {runnable}
instrumenter:
  start: | 
    "@scorep.user.region()"
  stop: |

env_variabbles: 
  SCOREP_ENABLE_TRACING: true
  SCOREP_EXPERIMENT_DIRECTORY: <profile_path>
