parallel: True
par_backend: MPI
language: py
extension: nc
format: netcdf4
create_command:
  serial: python {runnable}
create: |
  from typing import TypedDict
  import numpy as np
  import netCDF4


  class Form(TypedDict):
      shape: list[int]
      chunks: list[int]
      dtype: str


  class bcolors:
      HEADER = "\033[95m"
      OKBLUE = "\033[94m"
      OKCYAN = "\033[96m"
      OKGREEN = "\033[92m"
      WARNING = "\033[93m"
      FAIL = "\033[91m"
      ENDC = "\033[0m"
      BOLD = "\033[1m"
      UNDERLINE = "\033[4m"


  def create(
      path: str,
      variables: list[str] = [],
      shapes: list[list[int]] = [],
      chunks: list[list[int]] = [],
      datatypes: list[str] = [],
      parallel: bool = False,
      collective: bool = False,
  ):
      form: dict[str, Form] = {}
      for index, var in enumerate(variables):
          form[var] = {
              "shape": shapes[index],
              "chunks": chunks[index],
              "dtype": datatypes[index],
          }

      root = netCDF4.Dataset(path, "w", format="NETCDF4", parallel=False)
      root.createGroup("/")
      used = 0

      for variable, element in form.items():
          shape = element["shape"]
          chunk = element["chunks"]
          dtype = element["dtype"]

          dimensions = []

          for size in shape:
              root.createDimension(f"{used}", size)
              dimensions.append(f"{used}")
              used += 1

          if len(chunk) != 0:
              x = root.createVariable(variable, dtype, dimensions, chunksizes=chunk)
          else:
              x = root.createVariable(variable, dtype, dimensions)

          x[:] = np.random.random_sample(shape)

      root.close()
      print(f"{bcolors.OKGREEN}FINISHED{bcolors.ENDC}")


  #MAIN
run_command:
  serial: python {runnable}
  MPI: mpiexec -n python {runnable}
source: |
  from itertools import chain
  import time
  import math

  from mpi4py import MPI
  import netCDF4


  class bcolors:
      HEADER = "\033[95m"
      OKBLUE = "\033[94m"
      OKCYAN = "\033[96m"
      OKGREEN = "\033[92m"
      WARNING = "\033[93m"
      FAIL = "\033[91m"
      ENDC = "\033[0m"
      BOLD = "\033[1m"
      UNDERLINE = "\033[4m"


  #INSTRUMENTER_START
  def bench_helper(
      iterations: int,
      variables: list[str],
      dataset: netCDF4.Dataset,
      node: str,
      rank: int,
      rsize: int,
      collective: bool,
  ) -> list[tuple[str, str, str]]:
      bench: list[tuple[str, str, str]] = []
      for _ in range(iterations):
          if rank == 0:
              start = time.monotonic()

          for var in variables:
              try:
                  total_size: int = math.prod(dataset[var].shape)
                  size = int(total_size / rsize)
                  rstart = rank * size
                  rend = rstart + size

                  if collective:
                      print(
                          bcolors.OKBLUE + "Setting I/O to be collective" + bcolors.ENDC
                      )
                      dataset[var].set_collective(True)
                  else:
                      print(
                          bcolors.OKBLUE + "Setting I/O to be independent" + bcolors.ENDC
                      )

                  dataset[var][rstart:rend:]

              except KeyError:
                  print(f"Variable: {var} does not exist.")

          bench.append((str(rank), node, str(round(time.monotonic() - start, 32))))
          MPI.COMM_WORLD.Barrier()

      dataset.close()
      MPI.COMM_WORLD.Barrier()
      print(f"{bcolors.OKGREEN}FINISHED{bcolors.ENDC}")

      return bench


  def bench(
      path: str,
      iterations: int,
      variables: str,
      parallel: bool = False,
      collective: bool = False,
  ) -> list[tuple[str, str, str]] | None:

      dataset = netCDF4.Dataset(path, mode="r", format="NETCDF4", parallel=parallel)

      var_tmp = []
      comm = MPI.COMM_WORLD
      rank = MPI.COMM_WORLD.rank
      rsize = MPI.COMM_WORLD.size

      var_sizes: list[tuple[int, ...]] = []
      for var in variables:
          try:
              var_size: tuple[int, ...] = dataset[var].shape
              var_sizes.append(var_size)
              var_tmp.append(var)
          except KeyError:
              print(f"Variable: {var} does not exist.")
      print(
          f'for variable: {var_tmp} for engine: "netcdf4", rank: {rank}, size: {var_sizes}'
      )

      node = "None"
      if "SLURMD_NODENAME" in os.environ:
          node = os.environ["SLURMD_NODENAME"]

      result: list[tuple[str, str, str]] = bench_helper(iterations, var_tmp, dataset, node, rank, rsize, collective)

      gathered = comm.gather(result, root=0)
      if rank == 0:
          return list(chain.from_iterable(gathered))


  #MAIN
