parallel: configurable
par_backend: MPI
language: py
extension: zarr
format: zarr
create_command:
  serial: python {runnable}
  MPI: mpiexec -n python {runnable}
  profile: py-spy record --rate 100 --idle --subprocesses --full-filenames -F -n --format speedscope -o <profile_path>.json -- python {runnable}
  profile-MPI: mpiexec -n py-spy record --rate 100 --idle --subprocesses --full-filenames -F -n --format speedscope -o <profile_path>.json -- python {runnable}
create: |
  from hpffbench.func.datastruct import Datastruct
  from hpffbench.func.datastruct import Form


  def create_ds(
    form: dict[str, Form], path: str, parallel: bool = False, collective: bool = False
  ):

    ds_zarr = Datastruct()
    ds_zarr.create(
        path=path, form=form, engine="zarr", parallel=parallel, collective=collective
    )


  def create(
    path: str,
    variables: list[str] = [],
    shapes: list[list[int]] = [],
    chunks: list[list[int]] = [],
    datatypes: list[str] = [],
    parallel: bool = False,
    collective: bool = False,
  ):
    form: dict[str, Form] = {}
    for index, var in enumerate(variables):
        form[var] = {
            "shape": shapes[index],
            "chunks": chunks[index],
            "dtype": datatypes[index],
        }

    create_ds(form=form, path=path, parallel=parallel, collective=collective)

  #MAIN
run_command:
  serial: python -m scorep --thread=pthread --instrumenter-type=cTrace {runnable} -v
  MPI: mpiexec -n python -m scorep --mpp=mpi --thread=pthread --instrumenter-type=cTrace {runnable} -v
  profile: py-spy record --rate 100 --idle --subprocesses --full-filenames -F -n --format speedscope -o <profile_path>.json -- python {runnable} -v
  profile-MPI: mpiexec -n py-spy record --rate 100 --idle --subprocesses --full-filenames -F -n --format speedscope -o <profile_path>.json -- python {runnable} -v
source: |
  from hpffbench.func.datastruct import Datastruct

  def bench(
    path: str,
    iterations: int,
    variables: str,
    parallel: bool = False,
    collective: bool = False,
  ) -> list[int | float]:

    ds_zarr = Datastruct()
    ds_zarr.open(mode="r", engine="zarr", path=path)

    if parallel:
        ds_zarr.collective = collective
        ds_zarr.read(
            "bench_complete_parallel", variables=variables, iterations=iterations
        )
    else:
        ds_zarr.read("bench_complete", variables=variables, iterations=iterations)

    result = ds_zarr.log

    return result

  #MAIN
